name: progress_line
description: "A Flutter package to display the progress bar with a lot of personalization and make the progress percentage dynamic by using various colors and activating the animation."
version: 0.1.0
homepage: https://github.com/shervin-h/progress_line
repository: https://github.com/shervin-h/progress_line
issue_tracker: https://github.com/shervin-h/progress_line/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
